import pyautogui
script = "I HATE SUPERM I HATE SUPERM I HATE SUPERM I HATE SUPERMI HATE SUPERM I HATE SUPERM I HATE SUPERM I HATE SUPERMI HATE SUPERM I HATE SUPERM I HATE SUPERM I HATE SUPERMI HATE SUPERM I HATE SUPERM I HATE SUPERM I HATE SUPERMI HATE SUPERM I HATE SUPERM I HATE SUPERM I HATE SUPERM"

for x in script.split():
    pyautogui.write(x)
    pyautogui.press("enter")